# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='date',
            new_name='dateAttendance',
        ),
    ]
