# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 22:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20161117_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='dateAttendance',
            new_name='date_attendance',
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='departureTime',
            new_name='departure_time',
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='timeOfEntry',
            new_name='time_of_entry',
        ),
        migrations.RenameField(
            model_name='attendancerecord',
            old_name='workingPeriod',
            new_name='working_period',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='justification',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='justification',
            old_name='justificationType',
            new_name='justification_type',
        ),
        migrations.RenameField(
            model_name='justification',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='personalcontrol',
            old_name='monthYear',
            new_name='month_year',
        ),
        migrations.RenameField(
            model_name='workingperiod',
            old_name='departureTime',
            new_name='departure_time',
        ),
        migrations.RenameField(
            model_name='workingperiod',
            old_name='timeOfEntry',
            new_name='time_of_entry',
        ),
        migrations.RemoveField(
            model_name='personalcontrol',
            name='justifAbsencesDays',
        ),
        migrations.RemoveField(
            model_name='personalcontrol',
            name='leaveDays',
        ),
        migrations.RemoveField(
            model_name='personalcontrol',
            name='totalDays',
        ),
        migrations.RemoveField(
            model_name='personalcontrol',
            name='unjustifAbsencesDays',
        ),
        migrations.AddField(
            model_name='personalcontrol',
            name='justif_absences_days',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Only numeric characters', regex='^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='personalcontrol',
            name='leave_days',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Only numeric characters', regex='^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='personalcontrol',
            name='total_days',
            field=models.CharField(default=0, max_length=2, validators=[django.core.validators.RegexValidator(message='Only numeric characters', regex='^[0-9]*$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalcontrol',
            name='unjustif_absences_days',
            field=models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator(message='Only numeric characters', regex='^[0-9]*$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dni',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Only numeric characters', regex='^[0-9]*$')]),
        ),
    ]
